version: '3'
services:
  redis:
    image: redis:3.2.11-alpine
  db:
    image: postgres:10.1-alpine
    environment:
      - POSTGRES_DB=longbow
      - POSTGRES_USER=longbow
      - POSTGRES_PASSWORD=longbow
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    image: longbow_web
    command: python manage.py runserver 0.0.0.0:5721
    ports:
      - "5721:5721"
    depends_on:
      - db
    volumes:
      - .:/app
    env_file:
      - dev.env
  worker:
    image: longbow_web
    env_file:
      - dev.env
    command: python manage.py worker
  cluster:
    build:
      context: .
      dockerfile: Dockerfile.cluster