version: '3'
services:
  redis:
    image: redis:3.2.11-alpine
  db:
    image: postgres:10.1-alpine
    environment:
      - POSTGRES_DB=longbow
      - POSTGRES_USER=longbow
      - POSTGRES_PASSWORD=longbow
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    image: longbow_web
    command: python manage.py runserver 0.0.0.0:5721
    ports:
      - "5721:5721"
    depends_on:
      - db
    volumes:
      - .:/app
    env_file:
      - dev.env
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  worker:
    image: longbow_web
    env_file:
      - dev.env
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    command: python manage.py worker
  cluster:
    build:
      context: .
      dockerfile: Dockerfile.cluster
    volumes:
      - ~/.ssh:/root/.ssh
  jumper:
    image: longbow_web
    volumes:
      - ~/.ssh:/root/.ssh
    command: ssh -nN -R 8888:webapp:5721 ${GHAP_USERNAME}@${GHAP_IP}